### ISSUE TITLE
paths are hard coded for Linux

### ISSUE THREAD

**Issue by j2l** [felixbur/Emofilt#2]
After modifying the ini file I stumbled on various missing path and a missing file file, had to install mbrola for Windows (yay) to end up on a hard coded link (/ instead of \):
`java.io.FileNotFoundException: emofilt\test\testUs2.pho `throws Unknown path on Windows, even after creating the file.

```
emofilt.EmofiltPlayer - exec: mbrola E:\apps\mbrola\us2/us2 C:\temp\tmp.pho C:\temp\tmp.wav
java.io.IOException: Cannot run program "mbrola": CreateProcess error=2, Le fichier spécifié est introuvable
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.felix.util.Util.execCmd(Util.java:381)
        at emofilt.EmofiltPlayer.genWavFile(EmofiltPlayer.java:91)
        at emofilt.EmofiltPlayer.genWavFile(EmofiltPlayer.java:44)
        at emofilt.gui.MainControlsPanel$7.run(MainControlsPanel.java:177)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, Le fichier spécifié est introuvable
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 9 more
maxtime 10000 reached, giving up.
Wave file not found: C:\temp\tmp.wav
java.lang.IllegalArgumentException: Delete: no such file or directory: C:\temp\tmp.wav
        at com.felix.util.FileUtil.delete(FileUtil.java:233)
        at emofilt.EmofiltPlayer.playAndDelete(EmofiltPlayer.java:248)
        at emofilt.gui.MainControlsPanel$7.run(MainControlsPanel.java:178)
        at java.lang.Thread.run(Unknown Source)
```
E:\apps\mbrola\us2\us2, C:\temp\tmp.pho exist though

**Comment by felixbur** [comment]
Sorry for your troubles
Does it work when you call
mbrola E:\apps\mbrola\us2/us2 C:\temp\tmp.pho C:\temp\tmp.wav
on the commandline?

**Comment by j2l** [comment]
Actually "mbrola" is an unknown command on windows. 
MbrolaTools didn't install it.
Oh well, I can't take care of it right now. Let me know if you try it on windows and find a workaround.

**Comment by felixbur** [comment]
There's actually a emofiltConfig_windows.ini file in the distribution that should give some hints on how i run it under windows. Instead of mbrola i use phoplayer:
wavGenCmd|d:/Programme/Mbrola/phoplayer.exe

cheers,
Felix

**Comment by felixbur** [comment]
So no: "paths are not hard coded for Linux"
